export interface EmployeeAbsence {
  id?: string; // Unique identifier, auto-generated by Firestore
  employeeId: string; // Employee ID
  employeeName: string; // Employee name for display
  companyId: string; // Company ID
  startDate: string; // Start date in 'YYYY-MM-DD' format
  endDate: string; // End date in 'YYYY-MM-DD' format
  type: 'vacation' | 'sick' | 'personal' | 'other'; // Type of absence
  status: 'pending' | 'approved' | 'rejected'; // Approval status
  reason?: string; // Optional reason for absence
  notes?: string; // Optional notes
  createdAt: string; // Creation timestamp
  approvedBy?: string; // Manager UID who approved/rejected
  approvedAt?: string; // Approval timestamp
}

