export interface Employee {
  id?: string; // Unique identifier, auto-generated by Firestore
  name: string; // Employee's full name
  role: string; // Job title or position (e.g., "Manager", "Technician")
  phone: string; // Contact phone number
  companyId: string; // Unique identifier linking to the business
  services: string[]; // List of service IDs or names this employee can perform
  createdAt?: string; // Creation date, ISO format
  updatedAt?: string; // Last update date, ISO format
  selected?: boolean; // Optional flag for selection in UI forms
}
