export interface Review {
  id?: string; // Unique identifier, auto-generated by Firestore
  customer: string; // Name of the customer who left the review
  rating: number; // Rating score, typically 1 to 5
  comment: string; // Detailed feedback or comment
  companyId: string; // Unique علیهidentifier linking to the business
  createdAt?: string; // Creation date, ISO format
  updatedAt?: string; // Last update date, ISO format
}
